version: "3"
services:
  mycsvserver:
    image: "infracloudio/csvserver"
    container_name: infra-csvserver
    ports:
    - 9393:9300
    env_file:
    - ./csvserver.env
    volumes:
    - ./inputFile:/csvserver/inputdata
